services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
      - ./:/home/perplexica
      # - /home/perplexica/node_modules
      # - ./src:/home/perplexica/src
      # - ./public:/home/perplexica/public
      # - ./pages:/home/perplexica/pages
      # - ./components:/home/perplexica/components
      # - ./next.config.mjs:/home/perplexica/next.config.mjs
      # - /home/perplexica/node_modules  # prevent overwriting node_modules
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
