FROM node:20.18.0-slim AS builder

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true

WORKDIR /home/perplexica

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY . .
RUN mkdir -p /home/perplexica/data

FROM node:20.18.0-slim
WORKDIR /home/perplexica
COPY --from=builder /home/perplexica /home/perplexica
RUN mkdir -p /home/perplexica/uploads
CMD ["yarn", "dev"]