# docker-compose.override.remote.yml
services:
  app:
    build:
      dockerfile: Dockerfile.remote
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_AWS_DB_API_URL=https://lyxeetk4w1.execute-api.us-east-1.amazonaws.com/default/getFromStockalyzerDB
      - NEXT_PUBLIC_AWS_DB_API_KEY=0KcuAyP5zT8kk2vW4MXAU9lMi52Yorti4vRwLwia